[package]
name = "dhcp_server"
version = "0.1.0"
authors = ["ryoasu <ryoasu107@gmail.com>"]
edition = "2018"

[dependencies]
pnet="0.26.0"
byteorder="1"
log="0.4"
env_logger="0.6.1"
anyhow="1.0.32"
rusqlite="0.18.0"
ipnetwork="0.14.0"
